name: âœ¨ Next.js lint checks

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ğŸ”
        uses: actions/checkout@v2

      - name: Setup Node.js ğŸ«¡
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use a specific Node.js version, adjust as needed

      - name: Install Dependencies â˜˜ï¸
        run: npm ci # Use npm ci for faster and more consistent installs

      - name: Tests and Linting âœ…
        run: |
          npm run format  # Run Prettier to format code
          npm run lint    # Run linting checks
        # If any of the above steps fail, the workflow will stop

      - name: Production build âœ¨
        run: npm run build
        env:
          GENERATIVE_API_KEY: ${{ secrets.GENERATIVE_API_KEY }}
