name: âœ¨ Next.js lint checks

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ğŸ”
        uses: actions/checkout@v2

      - name: Setup Node.js ğŸ«¡
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install Dependencies â˜˜ï¸
        run: |
          npm install

      - name: lint Chacks âœ…
        run: |
          npm run lint

      - name: production build âœ¨
        run: |
          npm run build
